#!/bin/bash

# Creates the directory for a given day's experiments
time=$(date)
set $time

experiment_day="Experiment_"$1"_"$2"_"$3"_"$6
if ! test -d $experiment_day
  then
      mkdir $experiment_day
      echo $experiment_day
fi
echo $experiment_day
