#!/bin/bash

# Securely copies the latest files to the Japan instance in the Dirk group
# Version 07/08/2017
# Author Gloire Rubambiza
#file_list="../ReceiverDGJapan.py ../Bandwidth_Extraction_DGJapan ../Save_Estimate.py"
file_list="../Traceroute_Extraction_DGJapan ../Cleanup_Trace.py"
scp -r globaltrace ec2-user@ec2-52-199-106-184.ap-northeast-1.compute.amazonaws.com:pathload_1.3.2
