#!/bin/bash

# Logs into AWS virtual machine in Japan for Dirk Group
# Variable ECUs, 1 vCPUs, 2.5 GHz, Intel Xeon Family, 2 GiB memory, EBS only
ssh -i ~/.ssh/DirkGroup_Japan.pem -o 'IdentitiesOnly yes' ec2-user@$1
